### ISSUE TITLE
Can't set temperature for climate control

### ISSUE THREAD

**Issue by Hans5546** [ioBroker/ioBroker.hass#68]
Hello!

I use HASS to control some climate devices. 3 "modded" Midea (remko) ACs with ESPHome and 2 Tuya thermostats.

I can control these devices from HASS without any problems. Setting the mode (heat/ cool/ auto) is working, setting a target temperature also.

From IOBroker I can set the mode (for example cool) or other values like "low fan". But one thing does not work on any of my climate devices: Setting the temperature.
I tried different types for set temperature (mixed, number, ...), nothing.

I always get an error when setting the temperature to for example 22°C: "Cannot control hass.0.entities.climate.heidenfeld.set_temperature: true"
I
I already reinstalled the adapter from GIT (before I uses 1.0.3 from the IOBroker source), no change.

What else do you need? I already read, that there was a similar issue - but installing the GIT version did not help for me.

I have attached the objectdata for "set temperature" in my IOBroker.

Many thanks in advance!

[set_temperature.txt](https://github.com/ioBroker/ioBroker.hass/files/10139596/set_temperature.txt)

**Comment by Apollon77** [comment]
Please enable debug log for the instance and do such a control try. Grab then the full log (from that debug start) from disk under /opt/iobroker/log/... and post here ort send witjh reference to  this issue to me at iobroker@fischer-ka.de

**Comment by Hans5546** [comment]
Many thanks for the quick response!

I sent you an email with the debug log.

**Comment by Hans5546** [comment]
Hello Apollon,

did you get my email with the log? Otherwise I would send it again.

Many thanks!

**Comment by Apollon77** [comment]
Yes I received it. just had no time to look into it

**Comment by Apollon77** [comment]
Please try GitHub version. I also added new logs to provide more guidance.Please try if that would have helped

**Comment by Hans5546** [comment]
I tried to set the temperature to 22°C. I only set the value for "set temperature" in the HASS instance to 22°C and that's it.
The same way works for for example "cool" or "heat" - I only set the value for "HVAC Mode" to "cool" and it works.

In HASS itself I can use a temperature slider and some buttons to control my AC, that's working.

I will try the new GIT version, maybe it will take some time, as I am not at home at the moment and have only a VPN connection in my phone.

**Comment by Apollon77** [comment]
>  tried to set the temperature to 22°C

I expected that. It is a bit weird how this works "API Wise". it is a servcie and the dservice has fields. many services just have ONE Field and then the adapter already automatically use this one field. But in your case there are multiple fields; and multiple "number fields". so the adapter would not know what to set. That means you need to provide the JOSN string with the details what exactly you want to set.

When I find time somewhere maybe I find better ideas, but only usign the json it is possible to e.g. "set a new color for a lamp and also provide a fading time" and such (so parameter that belong together in one call

**Comment by DcFamas** [comment]
Same problem here. I also want to use my midea split device, but with the regular wlan stick. In HASS I can control this devices flawlessly. Is there anything I can support you Apollon to get this working? :)

**Comment by Apollon77** [comment]
Did you read te above posts? Please try to install GitHiub version and try to control ... it should give you a better info now what you need to provide

**Comment by DcFamas** [comment]
Oh sorry, I've overseen the json example "{"temperature":22}".
This works for me, thank you. :)

**Comment by Apollon77** [comment]
But it would be still interesting to see a rreal logging when you try to trigger it witl "just 22" :-) Then I could add this to readme as reference :-)

**Comment by DcFamas** [comment]
I'll work on it and give you a full list. :)

**Comment by Hans5546** [comment]
Hello,

sorry for the delay, I am back to home since yesterday. I updated to the new GIT-version and send you a new log.

At 2022-12-20 11:24:42.022 I set the temperature to 22°C -> does not work. I use the value "set temperature" as shown in the attached screenshot.

At 2022-12-20 11:25:06.181 I set the hvac_mode from "auto" to "head" -> works!

Maybe this helps? I do not know how to send a JSON string with the temperature integrated, maybe there is a solution?

Thanks in advance!

![set_temp](https://user-images.githubusercontent.com/5204791/208646152-4083cc25-389a-4a42-96ed-a789f48cca32.jpg)

**Comment by Apollon77** [comment]
As you tried to set 22 as value you got that warning in the log:

> 2022-12-20 11:24:42.031 - warn: hass.0 (13728) Please make sure to provide a stringified JSON as value to set relevant fields! Please refer to the Readme for details!
2022-12-20 11:24:42.031 - warn: hass.0 (13728) Allowed field keys are: temperature, target_temp_high, target_temp_low, hvac_mode

The idea was that this helps to see what needs/could to be done

**Comment by DcFamas** [comment]
Thank you! :)

**Comment by Apollon77** [comment]
Please set the loglevel to debug and post a full debug log from start and also when trying such actions. Please post as log file attachement here.

**Comment by DcFamas** [comment]
Here you go:
[midea.txt](https://github.com/ioBroker/ioBroker.hass/files/10307635/midea.txt)

**Comment by Apollon77** [comment]
@DcFamas Can you please send a complete debug log from adapterstart? Ineed to see how things are initialized in order to understand the errors

**Comment by Apollon77** [comment]
BTW: I found a bug on github preventing updating all values ...please someone install github and checl that all works and no "State changed for unknown object ..." messges are in log anymore

**Comment by Hans5546** [comment]
Hello again!

I did send you a log file via email with the new git version installed.

**Comment by DcFamas** [comment]
Hey @Apollon77,
installed GitHub version and sent you the log via. mail.
In the log I tried to set  {"swing_mode":"vertical"} which leads to the same error message.

There is a error in HASS:

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/midea_ac/climate.py:283
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: December 27, 2022 at 11:26:59 (8 occurrences)
Last logged: 08:25:02

    [myID] 'horizontal'
    [myID] 'horizontal'
    [myID] '{"swing_mode":vertical}'
    [myID] '{"swing mode":vertical}'
    [myID] ' {"swing_mode":"vertical"}'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/midea_ac/climate.py", line 283, in async_set_swing_mode
    self._device.swing_mode = ac.swing_mode_enum[swing_mode]
  File "/usr/local/lib/python3.10/enum.py", line 440, in __getitem__
    return cls._member_map_[name]
KeyError: 'vertical'`

Best regards :)

**Comment by Apollon77** [comment]
@DcFamas Ok, log looks cleaner. For your issue: 

When you see the log then the definition of that field is:

> 2023-01-02 08:24:01.073 - debug: hass.0 (501607) Found Entity service hass.0.entities.climate.midea_ac_16492674491898.set_swing_mode: {"desc":"Set swing operation for climate device.","read":false,"write":true,"type":"mixed"} / {"fields":{"swing_mode":{"name":"Swing mode","description":"New value of swing mode.","required":true,"example":"horizontal","selector":{"text":null}}},"entity_id":"climate.midea_ac_16492674491898","attr":"set_swing_mode","type":"climate"}

So this thing is exactly having one field with name "swing_mode", so normally just setting the value you want is compketely fine, no JSON needed here.

There is right now no logic that checks that "if it is just one field but a json is provided in this would be that field ... let me add that tomorrow ...

But in the meantime feel free to just enter "vertical" as value ...

**Comment by Apollon77** [comment]
PS: sttoooopppp ... according to log you entered the json sith a leading "space" character and this make the current algorithm not detect the json :-) GitHub version updated.

So it should work now with "just" the value "vertical" or with the json you provided before

**Comment by DcFamas** [comment]
Hey @Apollon77,
updatet to github version. Just "vertical" doesn't work:

`<html><body>


hass.0 | 2023-01-22 11:48:03.719 | error | Cannot control hass.0.entities.climate.midea_ac_myID.set_swing_mode: true
-- | -- | -- | --
hass.0 | 2023-01-22 11:48:03.718 | debug | got answer for call_service success = false, result = undefined
hass.0 | 2023-01-22 11:48:03.684 | debug | Send  to HASS for service set_swing_mode with climate and data  {"swing_mode":"vertical","entity_id":"climate.midea_ac_myID"}
hass.0 | 2023-01-22 11:48:03.684 | debug | Prepare  service call for  hass.0.entities.climate.midea_ac_myID.set_swing_mode with  (mapped) request parameters {"swing_mode":"vertical"} from value:  "vertical"


</body>
</html>`

But this is fine for me, I can deal with the JSON value. :)

Still I need the value, if the climate is on or off. Is it possible for you to build a new value for the object based on the log?

hass.0
	2023-01-22 11:47:03.620	debug	HASS-Message: State Changed: {"entity_id":"climate.midea_ac_16492674491898","state":"heat","attributes":{"hvac_modes":["auto","cool","dry","heat","fan_only","off"],"min_temp":17,"max_temp":30,"target_temp_step":1,"fan_modes":["Auto","Full","High","Medium","Low","Silent"],"preset_modes":["none","eco","boost"],"swing_modes":["Off","Vertical","Horizontal","Both"],"current_temperature":20,"temperature":25,"fan_mode":"Auto","preset_mode":"none","swing_mode":"Both","outdoor_temperature":3.5,"icon":"mdi:air-conditioner","friendly_name":"Klimaanlage","supported_features":57},"last_changed":"2023-01-22T10:47:03.611198+00:00","last_updated":"2023-01-22T10:47:03.611198+00:00","context":{"id":"01GQCHDENV4W2D6PDWV3TX0AH8","parent_id":null,"user_id":null}}

Turned from off to on:
`hass.0
	2023-01-22 11:47:03.620	debug	HASS-Message: State Changed: {"entity_id":"climate.midea_ac_myID",**"state":"heat"**,"attributes":{"hvac_modes":["auto","cool","dry","heat","fan_only","off"],"min_temp":17,"max_temp":30,"target_temp_step":1,"fan_modes":["Auto","Full","High","Medium","Low","Silent"],"preset_modes":["none","eco","boost"],"swing_modes":["Off","Vertical","Horizontal","Both"],"current_temperature":20,"temperature":25,"fan_mode":"Auto","preset_mode":"none","swing_mode":"Both","outdoor_temperature":3.5,"icon":"mdi:air-conditioner","friendly_name":"Klimaanlage","supported_features":57},"last_changed":"2023-01-22T10:47:03.611198+00:00","last_updated":"2023-01-22T10:47:03.611198+00:00","context":{"id":"anID","parent_id":null,"user_id":null}}`

Turned from on to off:
`hass.0
	2023-01-22 11:46:48.458	debug	HASS-Message: State Changed: {"entity_id":"climate.midea_ac_myID",**"state":"off**","attributes":{"hvac_modes":["auto","cool","dry","heat","fan_only","off"],"min_temp":17,"max_temp":30,"target_temp_step":1,"fan_modes":["Auto","Full","High","Medium","Low","Silent"],"preset_modes":["none","eco","boost"],"swing_modes":["Off","Vertical","Horizontal","Both"],"current_temperature":20,"temperature":25,"fan_mode":"Auto","preset_mode":"none","swing_mode":"Both","outdoor_temperature":10,"icon":"mdi:air-conditioner","friendly_name":"Klimaanlage","supported_features":57},"last_changed":"2023-01-22T10:46:48.452510+00:00","last_updated":"2023-01-22T10:46:48.452510+00:00","context":{"id":"anID","parent_id":null,"user_id":null}}`

Best regards :)

**Comment by DcFamas** [comment]
I'm stupid, the value exists already. :D
